### ISSUE TITLE
有关依赖的安装

### ISSUE THREAD

**Issue by harryisfish** [Press-One/prs-lib-py#1]
win10 和 ubuntu python 3.6下，这几个包

eth-keyfile
coincurve
eth-utls
eth-keys

的安装始终报错。是否存在特定版本才可以符合py3.6？

不知官方有没有遇到过这个问题。

是否可以用RSA替代？

**Comment by zh4n7wm** [comment]
发下你 Python 的具体版本呢？

无法安装的话，把报错信息也可以发下。
